saismrutiranjan18/Tiffin_Fusion

- ,github/ISSUE_TEMPLATE/bug_report.yml
- ,github/ISSUE_TEMPLATE/documentation_update.yml
- ,github/ISSUE_TEMPLATE/feature_request.yml
- ,github/PULL_REQUEST_TEMPLATE.md
@saismrutiranjan18 can you review my PR and add lables to it
> added workflow

- Dockerfile
1. **Ensure Directory Structure**  
Your project directory should include:
- `index.html` 
- Any additional assets (e.g., CSS, JavaScript) required by your site.
2. **Build the Docker Image**
Run the following command in the root of your project directory (where the `Dockerfile` is located):
```bash
docker build -t tiffin-fusion .
```
3. **Run the Docker Container**
Start a container from the built image:
```bash
docker run -d -p 8080:80 tiffin-fusion
```
4. **Access the Website**  
Open your browser and navigate to `http://localhost:8080`. You should see your website served.
> Dockerize application

- app.js
- index.html
- signin.css
- signin.html
- signin.js
- signup.html
- style.css
sign in sign up feature added with advance ui
> sign in sign up feature added in navbar with page

- index.html
- style.css
#10 solved   newsletter added to the footer section of home page .
> newsletter added to the footer section of home page

- index.html
> updated newsletter ui 

- index.html
- studentplan.css
- studentplan.html
- style.css
i have done these changes , if you want any improvement then tell me , i will give my best and accept this pull request .
https://github.com/user-attachments/assets/513cff33-1a6a-49da-b073-a0740a8d4420
> changes in student plan section

- app.js
- style.css
these are the changes and not it works properly
> updated student plan section

- index.html
- style.css
> contact header updated with bold font and red color

- index.html
Add hover effects and aligned all and add logo to it
> Updated footer with aligned and improved text

- contributors/contributor.css
- contributors/contributor.html
- contributors/contributor.js
- index.html
> contributors page added to website

- contributors/contributor.html
> updated contributor  page

- index.html
- privacy.html
#28 issue Solved , Add SWOC Labels to it @saismrutiranjan18                                                                                                                     Screenrecording :
https://github.com/user-attachments/assets/4af898bf-d419-4466-a511-05ce79cf4338
> Solved Privacy Policy Page added

- studentplan.css
I have fixed the overlapping of meal cards as well made somefew more changes as listed for better user experience.
Navigation Bar Enhancements: Improved visual clarity and spacing for better usability.
Card Flip Animation: Added smooth transitions to enhance interactivity and user engagement.
Card Design Improvements: Adjusted layout and font sizes for clean presentation.
Card Backface Styling: Enhanced visibility of content during the card flip animation.
Responsive Design Adjustments: Optimized layout for better display across various screen sizes.
Accessibility and User Experience Enhancements: Improved readability and hover effects for a more inclusive design.
https://github.com/user-attachments/assets/9d2eb609-cd6f-4469-b604-7194204a04e6
> changes done for overlapping of meal cards

- style.css
https://github.com/user-attachments/assets/073268bc-678e-41cc-9966-de8b7d19ff2e
> improvement in ui of 'why tiffin fusion' section with adv effects

- index.html
- style.css
improvement in appearance of this section in mobile ....
>  responsive design for why tf section

- index.html
This pull request addresses the alignment and visual issues in the footer and newsletter sections as outlined in issue #21 .
Key changes made : 
1.Footer Alignment:
Adjusted the alignment of the footer to ensure it properly fits the designated space.
Removed unnecessary spacing below the footer for a cleaner layout.
2.Newsletter Section Update:
Replaced duplicate images with a single relevant image that suits the concept.
Ensured the newsletter aligns seamlessly with the overall design.
Before :
After :
>  Enhanced Footer and Newsletter Alignment (#21)

- index.html
Reverts saismrutiranjan18/Tiffin_Fusion#39
> Revert " Enhanced Footer and Newsletter Alignment (#21)"

- index.html
now you can receive submission of form on your email .....
> Api added in contact us form

- index.html
- submitQuery.js
https://github.com/user-attachments/assets/d191aa58-fb69-443d-9252-2ff610f1d85b
> code of sumbmit query updated

- index.html
**Linked Issue:**  
Fixes #37  
**Description:**  
This PR addresses Issue #37 by integrating a **chatbot**  named **Tiffy** into the **Tiffin_Fusion** project to improve user experience through instant support, order guidance, and FAQs about meals, pricing, and delivery. This feature aims to drive engagement, simplify ordering, and enhance overall customer satisfaction.  
**Benefits of the Feature:**  
- **24/7 Customer Support:**  
- Handles frequent inquiries on meal options, pricing, and delivery schedules without requiring human support.  
- **Seamless Order Assistance:**  
- Aids users in placing and modifying orders efficiently.  
- **User Engagement:**  
- Promotes popular meals, recommends deals, and offers assistance with nutrition-related questions.  
I appreciate any feedback …
> Add Chatbot named "Tiffy" for Enhanced Customer Support and Order Assistance

- Terms.html
- index.html
#46 Issue fixed , Add SWOC labels to this PR. @saismrutiranjan18 , Terms and Conditions Page is accessed 
Screenrecording :
https://github.com/user-attachments/assets/18c9335c-23af-47c3-97a6-608f6fd494ff
> #46 Issue Fixed Terms&Conditions Page

- index.html
now the footer section links are working
> footer section responsive

- index.html
- style.css
here's the preview how it actually looks 
-
NOTE: i have added box shadow just for the video for clear view
-
https://github.com/user-attachments/assets/96a4eb4f-f99f-4d91-ac10-07fd29253b68
> updated footer to take the same box sizing as of newsletter

- contributors/contributor.css
- contributors/contributor.html
the updates are below 
Updated Navbar on Contributors Page:
The Contributors page now includes the updated navbar with the latest changes, including the "Meal Plan" button instead of the "Student Plan" button, as well as the new hover-triggered dropdown for meal plans.
Consistent Navbar Changes:
The hover effect on the "Meal Plan" and other navbar links is now consistent across both the main website and the Contributors page.
Dropdown functionality is triggered by hover, not click, and the list of plans (e.g., Student Plan, Corporate Plan, Daily Plan) is visible when hovering over "Meal Plan."
Other Navbar Links:
The rest of the navbar, like links to Home, Menu, About, Contact Us, and Sign In, is now consistent with the design you’ve applied on other pages.
All the changes like text hover …
> contributor page navbar updated

- dailyplans.css
- dailyplans.html
- index.html
so i have added daily plans page to your website with three custom plans that are below 
- Added **Oats Porridge with Fruits** for sustained energy and brain function.  
- Included **Boiled Eggs or Paneer Bhurji** for a protein boost to tackle morning tasks.  
- Introduced **Fresh Orange Juice** for a refreshing start packed with Vitamin C.
---
- Introduced **Dal Tadka** and **Jeera Rice** for a balanced combination of protein and carbs.  
- Added **Mixed Vegetable Sabzi** for essential vitamins and nutrients.  
- Enhanced with **Roti or Naan, Salad, and Pickle** for a complete and satisfying meal.
---
- Highlighted **Paneer Butter Masala** as a rich, protein-packed option.  
- Paired with **Veg Pulao or Plain Rice** and **Roti or Paratha** for a wholesome dinner.  
- Finished with …
> daily plans page added 

- README.md
- Server/Readme_Backend.md
- Server/api/app.js
- Server/vercel.json
Fixing #82 
Fixes and Changes:
Screenshot:
Auth using vercel deployed url
> Added Backend setup instruction

- app.js
- style.css
Features:
Responsive Adjustments for Mobile & Tablet:
Mobile (Phones): The button’s size and position adjust for small screens. The button shrinks to a 40px diameter and moves closer to the bottom-right corner to prevent interference with other elements. This ensures it’s always visible but unobtrusive.
Tablet Screens: On medium-sized devices, the button size is reduced to 45px, and its positioning is slightly adjusted to maintain visibility without overlapping key content.
Visibility Based on Scroll Position:
The button is hidden by default and only appears when the user scrolls down the page. Using JavaScript, the button becomes visible once the user scrolls 100px or more.
The button disappears when the user scrolls back to the top, maintaining a clean UI until needed.
Fixed Position: …
> top top scroll button css and js changed

- index.html
- style.css
> heading font changed

- Server/package-lock.json
- Server/package.json
- index.html
- style.css
Closes #73 
Replace the logo of navbar with the one used in footer
> Changed the Navbar logo image

- index.html
- menu-page/menu.css
- menu-page/menu.html
added menu page to the website with add button with effect on add button
> menu page added with add button

- blog.html
Closes #102 
Added empty blog pages that redirects from the main Blog. Added a separate folder for blogs to hold all the blogs.
> Added empty blog pages with seperate blog folder

- index.html
> link broken issue solved

- menu-page/menu.html
> favicon added to menu page

- signup.html
Closes #115 
Fixed logo visibility in signup page
> Fixed logos in signup page

- dailyplans/breakfast.html
- dailyplans/dinner.html
- dailyplans/lunch.html
#128 solved .. i have solved this issue links not working 
https://github.com/user-attachments/assets/ada76cd9-88e2-4253-a534-a2dd24978943
> links added

- dailyplans/breakfast.html
- dailyplans/dinner.html
- dailyplans/lunch.html
- menu-page/menu.html
https://github.com/user-attachments/assets/8602766e-4af5-435c-8913-a70f120ce5f7
#132 solved
I have added working navbar in menu page .....
> Nav bar added in menu page 

- menu-page/menu.html
#136 fixed 
https://github.com/user-attachments/assets/39955f31-1110-483d-8047-cdfc3e02200c
> nav bar issue fixed , now button is working

- index.html
- style.css
#141 issue closed
Edit Dropdown in Contact Us Section
> Edited dropdown in contact us

- index.html
- signin.html
- signup.html
Fixing #144 
I have fixed login and signup pages now they are working well
> Fixing login and signup page

- dailyplans/breakfast.html
- dailyplans/dinner.html
- dailyplans/lunch.html
#142  issue closed
Add theme colors to daily plan
> Add theme colors to daily plan

- index.html
- submitQuery.js
- work_with_us/work-with-us.css
- work_with_us/work-with-us.html
- work_with_us/work-with-us.js
"work us page added to website with fully working api and also with fully working navbar  .. #139 solved 
https://github.com/user-attachments/assets/6c85140d-5b2d-4bfa-9768-24ece4176784
> work us page added to website 

- index.html
- style.css
> Form with the Orange theme + Submit Button animations

- ,github/workflows/auto-comment.yml
Closes #154
GitHub actions added to automation of replying :
- New Issue is created
- New PR is submitted
- Any issue is closed
- Any PR is merged
> 🔗fix:Create auto-comment.yml

- index.html
https://github.com/user-attachments/assets/6edc1244-7441-4710-8fea-ea4e873e2f52
> Added signin sign out button

- contactUs.html
> #160 resolved

- .gitignore
- Server/controller/user.controller.js
- Server/createAdmin.js
- Server/middleware/chekAdmin.midddleware.js
- Server/models/user.model.js
- Server/routes/auth.routes.js
- adminSignin.html
- node_modules/.package-lock.json
- package-lock.json
- package.json
- signin.html
I have added admin backend for the app.
There is a file named `createAdmin.js` use that file to crreate a admin user
ScreenShot:
> Added admin panel backend

- index.html
Issue #172 
https://github.com/user-attachments/assets/454521cc-d5ec-4fc9-8358-efa55c4963c5
> Broken Link fixed

- index.html
- work_with_us/work-with-us.html
https://github.com/user-attachments/assets/c4c6f2bf#176 ac55-40e7-98f0-b72a6480e7de
#176 solved
> link added to term of services in footer 

- work_with_us/work-with-us.html
> favicon added to work with us page

- signin.html
> domain updated

- index.html
- style.css
> font size changed of sign in button of home page on navbar

- adminSignin.html
- adminindex.html
- signin.html
This is admin login
this is admin home page
> added admin pages

- work_with_us/work-with-us.css
- work_with_us/work-with-us.html
> footer added to work with us page

- contributors/contributor.html
- index.html
- menu-page/menu.html
- work_with_us/work-with-us.html
#187 solved .. now logo will workk... i have added link to all logos
> now logos are working on navbar

- blog.html
- corporateplans.html
- dailyplans.html
- studentplan.html
Added navbar at missing pages along with student_plan page
FIXES : #200 
Found some pages with missing navbars
Manual testing
> navbar added to pages

- index.html
- style.css
Styled the ui of signin button 
fixed #199 
- [✅ ] New feature (non-breaking change which adds functionality)
- [✅] My code follows the code style of this project.
> styled sign in button

- all_blogs/blog1.html
- all_blogs/blog2.html
- all_blogs/blog3.html
- blog.css
- blog.html
#195 issue solved
I have added blog pages individually
> Individual blog page is added

- package-lock.json
- signin.html
- signin.js
- signup.html
- signup.js
The toggle button for showing/hiding the password input does not work as expected. Clicking the button does not toggle the visibility of the password. I will Fix It . Now it works
The toggle button is an important feature for user experience, particularly for password inputs. Addressing this bug ensures better functionality and aligns with expected behavior, improving usability.
Manually
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
> Sign In page Password Toggle Bug Fix

- index.html
- style.css
Reverts saismrutiranjan18/Tiffin_Fusion#218
> Revert "Changes in the UI section"

- dailyplans.html
#205 solved footer added to daily plan page
> Footer added to daily meal plan page 

- corporateplans.css
- corporateplans.html
- studentplan.css
- studentplan.html
Fixed #207 
I have fixed the issues of student plan page and same issues are in corporate plan page and fixed that also.
- [✅] Bug fix (non-breaking change which fixes an issue)
- [ ✅] My code follows the code style of this project.
> fixed issues in studentplan page

- contributors/contributor.css
1. Changed title color 
2. Added bg-img 
3. Required styling.
**Issue:** #225
> CSS changed

- contributors/contributor.css
- contributors/contributor.js
**Issue:** #232 
https://github.com/user-attachments/assets/fdf81e1b-61a5-4bc1-a760-6330f6b3636c
> Responsiveness is rectified

- dailyplans.html
I fixed the issue where there was no access from the Daily Meal Plans page to the Homepage. Changes were made to enable seamless navigation from the Daily Meal Plans page to the Homepage.
This change was required to resolve the navigation issue, improving user experience by providing direct access to the Homepage from the Daily Meal Plans page. This ensures users can navigate the platform more intuitively.
I tested the changes by performing the following:
Verified that clicking the navigation button on the Daily Meal Plans page successfully redirects to the Homepage.
Conducted cross-browser testing to ensure consistent behavior across different browsers.
Confirmed there were no regressions affecting other parts of the application. …
> #220 [Bug] Fixed accessing Homepage from daily meal plans

- index.html
- report-fraud/report-fraud.css
- report-fraud/report-fraud.html
> Report fraud

- index.html
- whoweare.html
Added Who We Are page to the Website , 
@saismrutiranjan18 Add SWOC Labels to this Issue , Add Intermediate to this PR 
Screenrecording : 
https://github.com/user-attachments/assets/61df246f-5a16-468c-aba0-bfc20e4e7684
> Add Who we are Page to the Website

- index.html
Fixed Issue In Who we are page , @saismrutiranjan18 , Its Working Fine Now !
Screenrecording : 
https://github.com/user-attachments/assets/218b6f5d-e156-4466-9a4b-63f22d7fad82
> Fixed Who we are page

- index.html
I fix a small bug on index.html page. Please check
#Before -
#After-
> Fix a small bug on index.html page.

- lodgecomplaint.html
This page contains the content to be added for Lodge Complaint page
Closes #250 
- [x ] New feature (non-breaking change which adds functionality)
> Added contents to Lodge Complaint page

- menu-page/menu.css
This PR aims to add Responsiveness to the Menu Page.
Closes #184
> Made Menu page Responsive

- menu-page/cart.js
- menu-page/checkout.css
- menu-page/checkout.html
- menu-page/checkout.js
- menu-page/menu.css
- menu-page/menu.html
**Issue:** #253 
https://github.com/user-attachments/assets/3ad64224-0907-4dec-879a-4530591be776
> Added cart functionality

- menu-page/menu.css
- menu-page/menu.html
**Issue:** #255 
https://github.com/user-attachments/assets/efa9d6ce-48f8-48e5-82fe-5d9af5078625
- [ x] New feature (non-breaking change which adds functionality)
> Added search functionality in menu

- contributors/contributor.html
- corporateplans.html
Add a footer to the 'corporateplans.html' page, similar to the footer on other pages of the 'Tiffin Fusion' website.
I just edit the html page only.
I tested it on my local server.
#Before-
#After-
> Include a footer on the 'corporateplans.html' page.

- blog.html
- style.css
> added back button in blog.html

- menu-page/menu.html
> footer added to menu page

- index.js
The text animation in the navbar is slower than expected, i increase speed of it little bit.
The text animation in the navbar should be smooth, responsive, and fast enough to match the application's design standards, ensuring an optimal user experience.
manual.
https://github.com/user-attachments/assets/b367a7a2-3a74-451b-afab-843c717a9575
> fix bug : Navbar Text Animation is Slow

- corporateplans.html
- index.html
- menu-page/cart.js
- menu-page/menu.html
- studentplan.html
**Issue:** #268 
https://github.com/user-attachments/assets/2e978ba9-7110-44b2-9a2d-2a79de61eecd
> Card Item number

- adminSignin.css
- adminSignin.html
> Admin Sign in styling

- style.css
Hey @saismrutiranjan18, i have made the minor changes required to fix the issue, it is fixed now mentioned in issue #280
> #280 Fixed Newsletter Overlay

- investor-relations.css
- investor-relations.html
Fixes this issue : Investor relations page in the footer shows error404 #246 
(#246 )
there was no any investor relation page on this website but it was mentioned in the footer
so i designed and made this page
- designed this page with same color theme as of the whole website
- made it responsive so that it will look good in small devices also.
- kept the fonts consistent
This was required because *Investor relations* option in the footer was redirecting the users to a page that was giving Error404
and this can ruin the user experience
i have tested the design in multiple screen sizes
- it is responsive and clean looking in all screen sizes
horizontal screen view(for laptops , PCs)
vertical screen view( for mobiles, Taps etc. 
)
> designed investor relations page

- Server/api/app.js
- Server/controller/admin.controller.js
- Server/middleware/chekAdmin.midddleware.js
- Server/models/menu.model.js
- Server/routes/admin.routes.js
- Server/utils/cloudinary.utils.js
- package-lock.json
- package.json
I have added two controllers add meal plan and add menu items
Now we can use a admin panel frontend (which is yet to be implemented) for adding the meal plans instead of static data
it can be tested via postman . Steps:
1. after string the server , the addmenu end point is `http://localhost:3000/api/admin/addmenu` . You need to login to admin emal and pass and get the token. After that send the `Bearer token` with that reqest and the required fields `name,price,size,image` and the req body type will be `form-data`
2. for adding meal plan the endpoint is `http://localhost:3000/api/admin/addmealplan` , all steps are same as above just here will one more field that is `items` .
> initialinzed admin backend and added add meal plan controllers

- dailyplans/breakfast.html
- dailyplans/dinner.html
- dailyplans/lunch.html
footer added breakfast lunch  and dinner page 
https://github.com/user-attachments/assets/8907cc70-f219-47f1-9ca2-403615ba7f9d
> footer added to breakfast lunch and dinner plan

- menu-page/checkout.html
- menu-page/payments.css
- menu-page/payments.html
Implemented a responsive payments page where users can input their billing and payment details. Key features include:
- Displaying a success alert after payment completion.
- Clearing the cart post-payment.
- Redirecting the user to the home page for a seamless experience.
This feature was introduced to enhance the checkout process by:
- Providing users with clear feedback on payment success.
- Ensuring the cart is reset for subsequent orders.
- Improving navigation by redirecting users back to the home page.
The changes were tested in a local development environment through the following steps:
1. Filled out the payment form with valid details.
2. Submitted the form to trigger the payment flow.
3. Verified that:
- The success alert is displayed correctly.
- The cart is cleared.
- The …
>  Payments Page Implementation with Seamless Redirection

- menu-page/checkout.html
Added a navigation bar (navbar) to the checkout page for easier navigation. The navbar allows users to easily switch between different sections of the checkout process, enhancing the user experience and making the interface more intuitive.
The addition of the navbar addresses the need for improved navigation within the checkout page. Users can now seamlessly switch between different steps of the checkout process, which improves overall usability and user flow.
- Tested the navbar's functionality on the checkout page by:
1. Ensuring all links in the navbar are clickable.
2. Verifying that navigation between different sections works as intended.
3. Confirming that the navbar is responsive on various screen sizes.
*(Include relevant screenshots of the navbar and its functionality if …
> Added Navbar for Easy Navigation on Checkout Page

- studentplan.html
> Add footer on studentplan.html page

- style.css
In this update, a custom scrollbar design was implemented to improve the user experience and aesthetic appeal of the website. The scrollbar thumb is styled with the color `#80D0C7`, creating a soft, modern look that complements the overall theme of the page. The design also features a hover effect that changes the thumb color to `#66b2a5`, adding an interactive element for users. This custom scrollbar is applied across the entire page, ensuring a consistent look and feel.
1. **Targeting the Scrollbar**: The first step was to target the entire scrollbar using the `::-webkit-scrollbar` selector. I set its width and height to `12px` to create a narrow yet easily usable scrollbar.
2. **Styling the Scrollbar Thumb**: The `::-webkit-scrollbar-thumb` selector was used to style the draggable part …
>  Here's a refined title for your changes:  markdown Copy Edit # Implementation of Custom Scrollbar with Interactive Hover Effect

- blog.css
- blog.html
The styling of cards of Our blog page is not looks goods as it not contains any hover effect or animation.
The alignment of Cards is not done properly.
I've solved the issues
I've placed the cards properly and improved the alignment.
Added Hover effect.
Issue: #300 
Before:
After:
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to change)
- [x ] My code follows the code style of this project.
> Change the styling of Cards (Our blog Page)

- index.html
- testimonial.css
- testimonial.html
Hey @saismrutiranjan18  ,
Could you Please review and let me know if any further updates are needed and merge this PR under SWOC. 😊
It is Responsive across all Devices . 
Screenrecording : 
https://github.com/user-attachments/assets/97a0a8e9-3f87-4745-b5ec-77a36417a2bb
https://github.com/user-attachments/assets/d1776770-8f97-44b2-ae41-1571e808b4b1
> Added Testimonials Page

- Baselink.js
- Server/createAdmin.js
- Server/package-lock.json
- Server/package.json
- Server/routes/auth.routes.js
- admin-manage-user.html
- admin-meal-item.html
- admin-meal-plan.html
- adminindex.html
I have added admin pages to the site by this pages admins can manage the site. the backend part has to be implemented yet
https://github.com/user-attachments/assets/714d8fd6-7da5-4145-a750-8112726540e9
> added some admin pages

- style.css
Fixed UCON overlapping the header when scrolling, improving readability and user experience.
Resolved UI issue where UCON elements overlapped the header during scrolling. 
`Fixes` #323 
Tested on different screen sizes to ensure UCON stays properly positioned while scrolling.
> Fix: UCON Overlapping Issue

- menu-page/checkout.html
#330 
https://github.com/user-attachments/assets/70d42a13-f820-481f-babc-ace37be2c172
> hamburger fixed

- menu-page/checkout.css
- menu-page/checkout.html
- menu-page/checkout.js
Issue no:- #334 
Added increment and decrement for number of quantity of meals and displaying total bill amount
To give users an easy option to customize billing information
Tested on chrome browser
Making sure whether total price get updated or not
> Add bill and quantity features in checkout.js

- dailyplans/breakfast.html
- dailyplans/dinner.html
- dailyplans/lunch.html
- menu-page/menu.css
- menu-page/menu.html
Hey @saismrutiranjan18, i have made the respective changes and fixed the menu search overlap and the three sections within the daily plans section in the issue #322 
This has been tested across all devices and is responsive as well, the css has been taken care of as well, and the tutorial video's have been attached as well 
https://github.com/user-attachments/assets/1fcc296c-44a8-463a-96bf-98eb874924ba
https://github.com/user-attachments/assets/aee8f1cb-d8d0-4ba5-94a7-e42e61e040d8
> Fixed Menu Search Overlap and Daily Plans

- all_blogs/blog1.html
- all_blogs/blog2.html
- all_blogs/blog3.html
blog page ui fixed  same for all blogs #314 solved
> blog page ui fixed

- Server/controller/admin.controller.js
- Server/routes/admin.routes.js
- admin-meal-item.html
- adminSignin.html
i have added the add meal items frontend, admin usr can now add meal items from frontend
Fixing #339 
can be cheed from fontend
https://github.com/user-attachments/assets/a9b6889e-7ac8-4507-916a-76ff71b6cc70
> added manage meal items frontend

- contributors/contributor.js
total prs count added to contributors card and on contributors certificate
#341 solved
> total prs count added to contributors card and on contributors certificate

- .vscode/settings.json
- Server/controller/admin.controller.js
admins can now edit and delete mealplan and meal items
Fixing #345  also please add advance or beginner tag as i have to work with backend
Can be tested via postman . this are backend controllers. The routes are:
> added admin controllers like editing and deleteing mealplan and meal items

- contributors/contributor.css
- contributors/contributor.js
issue #348 
Added github icon
https://github.com/user-attachments/assets/a653e29b-4870-4c79-ba0e-dbdb05f1f059
> Added github icon in contributor card

- all_blogs/blog1.html
- all_blogs/blog2.html
- all_blogs/blog3.html
- blog.css
- blog.html
- contributors/contributor.css
- contributors/contributor.html
- corporateplans.css
- corporateplans.html
- dailyplans.css
- dailyplans.html
- dailyplans/breakfast.html
- dailyplans/dinner.html
- dailyplans/lunch.html
- index.html
- investor-relations.html
- menu-page/menu.css
- menu-page/menu.html
- report-fraud/report-fraud.css
- report-fraud/report-fraud.html
- studentplan.html
- style.css
- testimonial.css
- testimonial.html
- whoweare.html
#336  Adding payment options in footer
@saismrutiranjan18 
Adding acceptable payment options (frontend) to the footer to make it easier for customers to know the accepted payment methods upfront.
This feature is important for the users to understand the types of payments are accepted.
> Added payment options in footer #336

- 404.html
#351 solved 
https://github.com/user-attachments/assets/5ea3d82b-1c13-460d-867c-d301a6c0c0be
> customize 404 error page added

- Server/controller/resturant.controller.js
- Server/models/restrurant.model.js
I have added separate controllers for register and login of tiffincentres and resturants. They can also add or remove meal plans . I used separate model for this for better access to each parrt
> added separate controller for resturant and tiffin centres

- dark-mode.js
- index.html
- style.css
fixes: #357 
Implemented dark mode
> Implemented dark mode

- addBlog.html
I have added add blog frontend.
> added add blog frontend

- index.html
- style.css
> Dark mode Bug fix issue:-#376

- style.css
fixes: #371 
Added transition to the social link icons
> Applied transition to the social links

- lodgecomplaint.html
Hey @saismrutiranjan18 , Could you please review and merge this under SWOC .
Screenrecording : 
https://github.com/user-attachments/assets/64256fe9-25cb-474e-8130-a50d65f62e8d
> Navbar and footer issue fixed in Lodge Complaint

- style.css
Added new lines darkmode-dropdown, darkmode-dropdown:hover and darkmode-dropdown:active which makes the meal elements visible in dark mode.
This change is required as without this the dropdown elements were not visible in dark mode.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
> Added new css lines to make the meal plan dropdown elements visible in dark mode.

- style.css
> footer added for dark mode  for home page

- dailyplans.html
- style.css
> working navbar added to daily meal plan page 

- dailyplans.html
- dailyplans/lunch.html
- style.css
> navbar added to lunch plan 

- dailyplans.html
- dailyplans/dinner.html
- dailyplans/lunch.html
- style.css
> navbar added to dinner plan page 

- dailyplans.html
- dailyplans/breakfast.html
- dailyplans/dinner.html
- dailyplans/lunch.html
- style.css
> navbar added to breakfast plan page 

- contactUs.html
- contributors/contributor.css
- contributors/contributor.html
- contributors/contributor.js
- corporateplans.html
- dailyplans.html
- index.html
- investor-relations.html
- lodgecomplaint.html
- security.html
- studentplan.html
- whoweare.html
> dark mode in all pages

- dailyplans/breakfast.html
- dailyplans/dinner.html
- dailyplans/lunch.html
- index.html
- menu-page/cart.js
- menu-page/checkout.html
- menu-page/checkout.js
- menu-page/menu.html
- studentplan.html
- style.css
Adding a thumbnail image and meal type in the checkout cart
> Adding meal type and image thumbnail

- menu-page/checkout.html
The back button of checkout page was not working.
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the code style of this project.
> Fixed the back button

- Server/routes/payment.routes.js
- Server/server.js
- menu-page/payments.html
Created the payment gateway using Stripe.
- [X ] Breaking change (fix or feature that would cause existing functionality to change)
> Added the payment gateway

- style.css
> darkmode  added to footer of home page 

- ReusableModal.js
- all_blogs/blog1.html
- all_blogs/blog2.html
- all_blogs/blog3.html
- blog.html
- contactUs.html
- contributors/contributor.html
- corporateplans.html
- dailyplans.html
- dailyplans/breakfast.html
- dailyplans/dinner.html
- dailyplans/lunch.html
- index.html
- investor-relations.html
- lodgecomplaint.html
- menu-page/menu.html
- report-fraud/report-fraud.html
- security.html
- studentplan.html
- testimonial.html
- whoweare.html
The "Added to the Cart", pop up message for clicking the "Add +" button. Also in some cases the Navbar's and Footer's hyperlink was modified. Also in "Security" tab and "Get in Touch" tab the Navbar's UI is updated.
To have a better experience.
1. https://github.com/saismrutiranjan18/Tiffin_Fusion/issues/411
2. https://github.com/saismrutiranjan18/Tiffin_Fusion/issues/410
The Video link of the changes - https://drive.google.com/file/d/1sN24oB45Nh4Xq1GfP1wXi7ibI_g4YINs/view?usp=sharing
> Added to cart pop up message, and improvement of Navbar & Footer functionality

- 404.html
animated 404 error page updated 
#410 solved
> 404 page updated

- style.css
added more hover effects on view more and see our blog buttons.
issue no #420
> Improve the view more and see our blog buttons

- 404.html
closes #419 
The redirecting issues have been fixed.
apertre2.0
> fixed issues of 404 page

- 404.html
- style.css
> favicon added to 404 error page 

- 404.html
- security.html
- style.css
> Security page hamburger fixed 

- 404.html
- security.css
- security.html
- style.css
#429 solved 
https://github.com/user-attachments/assets/3b0f9141-4db4-46d5-966a-ca6f83acdb64
> security page ui improved and darkmode added 

- security.html
> favicon added to security page

- contributors/contributor.js
- lodgecomplaint.html
- privacy.html
- security.html
- style.css
> Contributor page limit increased to 200 

- lodgecomplaint.html
- security.html
> favicon added to lodge complain page 

- lodgecomplaint.html
- privacy.html
- security.html
> footer added to privacy page 

- lodgecomplaint.html
- privacy.html
- security.html
> Navbar added to privacy page 

- lodgecomplaint.html
- privacy.html
- security.html
- style.css
> tiffin center card updated for dark mode 

- index.html
- style.css
Aligned Customize Menu Button & Improved Styling
- **Center-aligned** the **Customize Menu button** on **large screens**.
- **Moved** all styling to **style.css** for better maintainability. 
- Replaced `<a> tag` with a `<button>` for the **Customize Menu button**  and **View More button**.
- Changed the View More button **hover** color from **blue** to **red**.
- Added **dark mode support** for the Customize Menu button.
fixes #447 
These changes improve UI consistency, accessibility, and maintainability. The styling is now centralized in style.css, and the button elements are more semantically correct.
- Manually tested responsiveness across different screen sizes.
- Verified dark mode styling for the Customize Menu button.
- Ensured the View More button correctly changes color on …
> fixed customize menu button alignment

- Terms.html
> footer added to term of services page 

- Terms.html
> navbar added to term of services page

- menu-page/checkout.css
Fixed the checkout page and made the page more responsive.
> Made the checkout page more responsive

- contributors/contributor.js
- menu-page/menu.html
> Certificate added for apertre 2.0

- menu-page/menu.html
> menu page navbar styling changed

- contributors/contributor.js
- menu-page/menu.html
- menu-page/payments.html
#464 done 
https://github.com/user-attachments/assets/7cf83e60-1b34-4317-97a9-793cb4eae16a
> Loader added for payment page 

- contributors/contributor.js
- menu-page/menu.html
- menu-page/payments.html
#468 solved 
https://github.com/user-attachments/assets/f6adad08-6775-49bd-9d21-f097e1d99747
> Loader added for menu page 

- index.html
> Seo meta tags  added 

- corporateplans.html
- customize-menu.html
- dailyplans.html
- studentplan.html
> loader added to customize menu plan page 

- admin-manage-orders.html
- admin-manage-user.html
- admin-meal-item.html
- admin-meal-plan.html
- adminindex.html
#486 solved 
https://github.com/user-attachments/assets/4de04168-c200-4b6e-a119-38342068d7f4
> Manage orders admin panel created 

- .vscode/settings.json
- style.css
Changes the view full menu button 
Closes #489
> Changes the view full menu button

- .vscode/settings.json
- style.css
Changes the menu section
Fixes #490
> Changes the menu section

- customize-menu.html
- menu-page/checkout.html
> Footer added to cart page 

- customize-menu.html
> favicon added to customize menu page

- corporateplans.css
- corporateplans.html
- customize-menu.html
- menu-page/checkout.html
#520 solved 
https://github.com/user-attachments/assets/362f92c5-6bcb-4d0f-9c9e-a80c032782d3
> corporate meal plan page redesigned with filtering system

- studentplan.css
- style.css
> Add effects to the button

- studentplan.css
- style.css
> Update the student plan section  Issue :#453

- studentplan.css
- style.css
> Update the menu section

- studentplan.css
- style.css
> Changes the navbar

- style.css
Reverts saismrutiranjan18/Tiffin_Fusion#500
> Revert "Update the menu section"

- studentplan.css
Reverts saismrutiranjan18/Tiffin_Fusion#497
> Revert "Update the student plan section  Issue :#453"

- style.css
Reverts saismrutiranjan18/Tiffin_Fusion#502
> Revert "Changes the navbar"

- style.css
#534  solved 
https://github.com/user-attachments/assets/e0f09504-466a-4e49-85f6-60ea3c58868b
> menu section fixed and now responsive

- adminSignin.html
Dummy Credentials:
Added two dummy admin accounts:
Email: admin1@tiffinfusion.com, Password: AdminPass123
Email: admin2@tiffinfusion.com, Password: SecurePass456
These are checked client-side before attempting the Axios call.
#537 solved 
https://github.com/user-attachments/assets/78fbef9e-180a-45c1-bbf1-ad19bf8ea18c
> dummy credentials created to access admin dashboard

- customize-menu.html
- dailyplans.css
- dailyplans.html
- dailyplans/breakfast.css
- dailyplans/breakfast.html
- dailyplans/dinner.css
- dailyplans/dinner.html
- dailyplans/lunch.css
- dailyplans/lunch.html
- index.html
- studentplan.css
- studentplan.html
- work_with_us.css
- work_with_us.html
> customize menu button link updated and foter added to customize menu page"

- dailyplans.css
- dailyplans.html
- dailyplans/breakfast.css
- dailyplans/breakfast.html
- studentplan.css
- studentplan.html
#545 solved 
https://github.com/user-attachments/assets/a7b31a4c-dcd9-4585-a4d7-39e12636cadb
> Breakfast page redesigned  with responsiveness 

- index.html
- style.css
Corrected the **title styling in dark mode** for better readability. Also updated **“we Accept”** to “**We accept”** in the footer for consistent text formatting.
Fixed the title styling issue in dark mode to ensure proper visibility. Also corrected the footer text from “we Accept” to “We accept” for consistency in capitalization.
Fixes #506 
Tested locally by switching between light and dark modes to verify the title styling. Checked footer section to confirm the corrected text appears as expected.
> fix minor changes

- style.css
Changes the view more button in dark mode.
Closes issue no #504
> Changes the view more button in dark mode

- lodgecomplaint.html
#555  solved 
https://github.com/user-attachments/assets/2eb75a2d-7552-45f6-9882-dec3146cf55a
>  lodge complaint page redesined with updated footer and navbar and dark mode 

- blog.html
- customize-menu.html
> Hamburger issue fixed of blog page 

- customize-menu.html
customize menu added for everyday
#557 solved
> customize menu added for everyday

- blog.css
- blog.html
> blog page ui updated and dark mode also added with updated navbar

- all_blogs/blog1.html
- all_blogs/blog2.html
- all_blogs/blog3.html
#564 added 
https://github.com/user-attachments/assets/9fff8927-895f-435c-ac92-321550df3744
> custom loader added to every blog page

- contributors/contributor.js
certificates updated according to march 7 to april 13
#566 solved
for example
> certificates updated according to march 7 to april 13
